### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Buy-One**
Added Mespotine's website to Documentation links

### CODE REVIEW

**Comment by indiscipline** [comment]
I'm sorry, I was explicitly and personally told by this person they don't want being mentioned or any of their work being featured here, for some reason.

We can reopen this as soon as any of the committers receives a personal permission from the author that can be linked/quoted in the PR to avoid potential conflicts.

As far as I know, at the moment of writing the person in question can be reached on the Reaper forums or in some of the more established Reaper Discord communities.

**Comment by Buy-One** [comment]
OK. Extremely, i'd say shockingly strange, considering that the website is freely accessible on the Web.

**Comment by Suzuki-Re** [comment]
Shouldn't this be mentioned as label:exclusion in the issue?

**Comment by indiscipline** [comment]
> Shouldn't this be mentioned as label:exclusion in the issue?

As soon as anyone opens a relevant issue I'll mark it and will link to the explanation here. Don't want to specifically create an issue mentioning someone who asked for maximum privacy.

**Comment by Suzuki-Re** [comment]
That makes sense. Thank you.

**Pull request closed without merging**
